title: Johanna
# email: johannadinicola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Johanna Maria DiNicola lives in Malden, MA with her mom and dad.
logo: "/assets/img/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johannadinicola.com" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata]
show_excerpts: true
future: false
paginate: 5
plugins: 
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
