title: Johanna
# email: johannadinicola@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Johanna Maria DiNicola lives in Malden, MA with her mom and dad.
logo: "/assets/img/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johannadinicola.com" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata]
show_excerpts: true
# paginate: true
# plugins: 
#   - jekyll-paginate
