#!/usr/bin/env ruby
# frozen_string_literal: true

require 'w3c_validators'

def validator(file)
  case File.extname(file)
  when '.html'
    W3CValidators::NuValidator.new
  when '.xml'
    W3CValidators::FeedValidator.new
  when '.css'
    W3CValidators::CSSValidator.new
  end
end

def validate(file)
  puts "Checking #{file}..."

  path = File.expand_path "../_site/#{file}", __dir__
  results = validator(file).validate_file(path)

  return puts 'Valid!' if results.errors.empty?

  results.errors.each { |err| puts err.to_s }
  exit 1
end

validate 'index.html'
validate File.join 'page2', 'index.html'
validate File.join 'posts', '2020', '10', '10', 'welcome-home-johanna.html'
validate File.join 'posts', '2020', '10', '11', 'johanna-will-see-you-now.html'
validate '404.html'
validate File.join 'assets', 'css', 'style.css'
