name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.4"
          bundler-cache: true

      - run: bundle exec script/cibuild
