name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.4"
      - name: Bootstrap
        run: sh script/bootstrap

      - name: Build
        run: bundle exec script/cibuild
